"""Add ai_analysis_started_at to PullRequestResult

Revision ID: 0935ec689370
Revises: 73769f8443ae
Create Date: 2025-07-02 15:29:26.853421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0935ec689370'
down_revision: Union[str, None] = '73769f8443ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request_events')
    with op.batch_alter_table('pull_request_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_request_results', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis_started_at')

    op.create_table('pull_request_events',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pr_node_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('event_time', sa.DATETIME(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['pr_node_id'], ['pull_requests.pr_node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
