"""add unique constraint to user.github_url

Revision ID: 097061bb15b8
Revises: be9a3b35334e
Create Date: 2025-07-03 18:29:55.672064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097061bb15b8'
down_revision: Union[str, None] = 'be9a3b35334e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request_events',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pr_node_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('event_time', sa.DATETIME(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['pr_node_id'], ['pull_requests.pr_node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
