"""20250917_1206_merge_pr_models_into_single_file

Revision ID: 2a0ea2c4ee3d
Revises: 5bc92eb05eb5
Create Date: 2025-09-17 12:06:12.404081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0ea2c4ee3d'
down_revision: Union[str, None] = '5bc92eb05eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
