"""20250916_1835_optimize_user_identity_model

Revision ID: 45f092440e63
Revises: 2caffbfc83a2
Create Date: 2025-09-16 18:35:19.369422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f092440e63'
down_revision: Union[str, None] = '2caffbfc83a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_column('verification_expires_at')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('contribution_count')
        batch_op.drop_column('oauth_scope')
        batch_op.drop_column('oauth_expires_at')
        batch_op.drop_column('location')
        batch_op.drop_column('oauth_refresh_token')
        batch_op.drop_column('oauth_access_token')
        batch_op.drop_column('company')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('oauth_access_token', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('oauth_refresh_token', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('oauth_expires_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('oauth_scope', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('contribution_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verification_expires_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
