"""Add department_id to User model

Revision ID: 4d3cb1cc4f64
Revises: 
Create Date: 2025-07-01 14:49:19.890184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3cb1cc4f64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_department', 'departments', ['department_id'], ['id'])
        batch_op.drop_column('department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_user_department', type_='foreignkey')
        batch_op.drop_column('department_id')

    op.create_table('pull_request_events',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pr_node_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('event_time', sa.DATETIME(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['pr_node_id'], ['pull_requests.pr_node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_snapshots',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_points', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
