"""20250917_1135_update pr metrics 

Revision ID: 5bc92eb05eb5
Revises: c40d6abb957f
Create Date: 2025-09-17 11:35:08.816573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc92eb05eb5'
down_revision: Union[str, None] = 'c40d6abb957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observability', sa.Float(), nullable=True))
        batch_op.drop_column('documentation_completeness')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentation_completeness', sa.FLOAT(), nullable=True))
        batch_op.drop_column('observability')

    # ### end Alembic commands ###
