"""20250917_1828_update mall models

Revision ID: 62e0d2a323dc
Revises: 2a0ea2c4ee3d
Create Date: 2025-09-17 18:28:31.830308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e0d2a323dc'
down_revision: Union[str, None] = '2a0ea2c4ee3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mall_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_mall_categories_company_id_companies')),
    sa.ForeignKeyConstraint(['parent_id'], ['mall_categories.id'], name=op.f('fk_mall_categories_parent_id_mall_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mall_categories'))
    )
    op.create_table('mall_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('initial_stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_limited', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_mall_items_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mall_items'))
    )
    with op.batch_alter_table('mall_items', schema=None) as batch_op:
        batch_op.create_index('idx_mall_items_available_stock', ['is_available', 'stock'], unique=False)
        batch_op.create_index('idx_mall_items_company_category', ['company_id', 'category'], unique=False)
        batch_op.create_index('idx_mall_items_featured_sort', ['is_featured', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_points_cost'), ['points_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_mall_items_stock'), ['stock'], unique=False)

    op.drop_table('rewards')
    op.drop_table('redemptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemptions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('reward_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=200), nullable=True),
    sa.Column('available', sa.BOOLEAN(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mall_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mall_items_stock'))
        batch_op.drop_index(batch_op.f('ix_mall_items_sort_order'))
        batch_op.drop_index(batch_op.f('ix_mall_items_points_cost'))
        batch_op.drop_index(batch_op.f('ix_mall_items_name'))
        batch_op.drop_index(batch_op.f('ix_mall_items_is_available'))
        batch_op.drop_index(batch_op.f('ix_mall_items_company_id'))
        batch_op.drop_index(batch_op.f('ix_mall_items_category'))
        batch_op.drop_index('idx_mall_items_featured_sort')
        batch_op.drop_index('idx_mall_items_company_category')
        batch_op.drop_index('idx_mall_items_available_stock')

    op.drop_table('mall_items')
    op.drop_table('mall_categories')
    # ### end Alembic commands ###
