"""20250917_1128_update pr models

Revision ID: c40d6abb957f
Revises: 45f092440e63
Create Date: 2025-09-17 11:28:44.467251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40d6abb957f'
down_revision: Union[str, None] = '45f092440e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('code_quality', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('innovation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('documentation_completeness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('performance_optimization', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('innovation_bonus', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_pr_metrics_quality_score')
        batch_op.create_index(batch_op.f('ix_pr_metrics_total_score'), ['total_score'], unique=False)
        batch_op.drop_column('collaboration_bonus')
        batch_op.drop_column('quality_bonus')
        batch_op.drop_column('quality_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('quality_bonus', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('collaboration_bonus', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_pr_metrics_total_score'))
        batch_op.create_index('ix_pr_metrics_quality_score', ['quality_score'], unique=False)
        batch_op.drop_column('innovation_bonus')
        batch_op.drop_column('performance_optimization')
        batch_op.drop_column('documentation_completeness')
        batch_op.drop_column('innovation')
        batch_op.drop_column('code_quality')
        batch_op.drop_column('total_score')

    # ### end Alembic commands ###
